---
name: Bump version
on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Which version component to bump'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bumpversion:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1

      - name: Install bumpversion
        run: |
          python -m pip install bump2version

      - name: Bump version and push main & tags
        # Figure out how to get this from the user that launched the workflow
        run: |
          set -e
          # Ensure git has a username (to allow the commit)
          git config --local user.name "github-actions[bot]"
          git config --local user.email '${{ github.event.sender.id }}+${{ github.event.sender.login }}@users.noreply.github.com>'

          # Bump version
          bumpversion ${BUMP_LEVEL}

          # Push update commit & tags back to repo
          git push origin main --tags
        env:
          BUMP_LEVEL: ${{ inputs.bump_level }}
